#lang racket
(define NUMIN 1024)
(define (cs s)
  (if (string? s)
      (let ((str s))
        (do ((i 0 (+ i 1)))
          ((>= i NUMIN))
          (if (>= i (string-length s))
              (printf "~A " 32)
              (printf "~A " (char->integer (string-ref s i)))
              )
          )
        )
      (error "not string")
      )
  )